CREATE DATABASE IF NOT EXISTS socialnet;
USE socialnet;

CREATE TABLE IF NOT EXISTS account (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    fullname VARCHAR(200) NOT NULL,
    password VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY 'Abc123';
GRANT ALL PRIVILEGES ON socialnet.* TO 'admin'@'localhost';
FLUSH PRIVILEGES;